# Generated by Django 5.1.6 on 2025-02-20 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UzSentTokenization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'UzSentTokenization',
                'verbose_name_plural': 'UzSentTokenizations',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['word'], name='word')],
            },
        ),
        migrations.CreateModel(
            name='Yuklamalar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word_yuklamalar', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Yuklamalar',
                'verbose_name_plural': 'Yuklamalar',
                'indexes': [models.Index(fields=['word_yuklamalar'], name='word_yuklamalar')],
            },
        ),
    ]
